# utility functions (general)
import os

def make_file_path(file_name: str, id: str) -> str:
    """Make file path for user-uploaded file by concatenating original file name and id

    Args:
        file_name (str): name of file uploaded by user
        id (str): unique id generated by uuid library in TypeScript

    Returns:
        str: unique file name
    """
    base, file_type = os.path.splitext(file_name)
    return f'{base}_{id[:10]}{file_type}'

def undo_file_path(file_path:str) -> str:
    base, ext = os.path.splitext(file_path)
    return f'{base[:-11]}{ext}'